### ISSUE TITLE
UI components are not getting rendered properly.

### ISSUE THREAD

**Issue by YadavGulshan** [YadavGulshan/MedAlthea#34]
![image](https://user-images.githubusercontent.com/63960580/154324267-8b6d809d-3311-4566-a2f0-d6c222dc33b1.png)

Login button whose task is to route the user from sign up screen to login is also not working.

**Comment by rahul007-bit** [comment]
please make a new pull and check!!!!

**Comment by YadavGulshan** [comment]
Still the same.....

**Comment by YadavGulshan** [comment]
![image](https://user-images.githubusercontent.com/63960580/154791943-2123cf88-df99-4cbe-af38-05df18e2e323.png)

**Comment by YadavGulshan** [comment]
That Already a member thing has issues in both login and register section.

**Comment by rahul007-bit** [comment]
it will be updated soon!!👍🏼
