### ISSUE TITLE
Unable to check available username

### ISSUE THREAD

**Issue by rahul007-bit** [YadavGulshan/MedAlthea#46]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/67467792/155146886-a374593b-afe9-4804-998f-568c9c1abfc5.png">

why do we should have AccessToken to check whether the username is available to assign to a new user 🤔

**Comment by rahul007-bit** [comment]
well it's `register/search/?search=username`

**Comment by YadavGulshan** [comment]
> well it's `register/search/?search=username`
> 

Yep
